export const metadata = {
  title: 'EditDottedPicture',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <head>
        <meta charSet={"utf-8"} />
      </head>
      <body>{children}</body>
    </html>
  )
}
